from time import sleep
import os
def load():
   print('|                                           |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■                                          |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■                                         |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■                                        |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■                                       |')
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■                                      |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■                                     |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■                                    |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■                                   |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■                                  |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■                                 |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■                                |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■                               |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■                              |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■                             |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■                            |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■                           |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■                          |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■                         |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■                        |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■                       |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■                      |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■                     |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■                    |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■                   |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■                  |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■                 |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■                |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■               |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■              |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■             |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■            |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■           |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■          |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■         |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■       |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■      |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■     |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■    |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■   |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■  |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ |')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■|')
   sleep(0.1)   
   os.system('cls' if os.name == 'nt' else 'clear')
   print('|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■|✓')

load()